# Generated by Django 5.2.5 on 2025-09-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_size_slug_alter_product_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='description',
        ),
    ]
